debug: true
demo: false
db: mysql
mysql:
  hostname: 172.16.101.32
  port: 3306
  username: root
  password: mysql
  database: next-terminal
sqlite:
  file: 'next-terminal.db'
server:
  addr: 0.0.0.0:8088